Feature/ot167 16
alkemyTech/OT167-Java-server pull request #12
Opened 2022-03-19 02:01 UTC by lucianoLattante

2022-03-19 02:09 UTC, turcoamado requested changes
Te marqué unas pavadas, el código acordate que tiene que ser en inglés.
El archivo properties no debería estar incluído en el commit, es propio de cada configuración local

2022-03-19 02:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Role.java
> +    @Column(name = "descripcion")
El nombre debería estar en inglés

2022-03-19 02:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Role.java
> +    public Role() {
En lugar de crear los constructores y los getters y setters podes utilizar **Lombok**

2022-03-19 02:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Role.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Chequeate el formato que van a utilizar para la fecha cosa de que todos utilicen el mismo, me parece bien que agreguen la hora también, pueden debatirlo así se ponen de acuerdo

2022-03-19 02:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/repository/RoleRepository.java
> +public interface RoleRepository extends JpaRepository<Role, Long> {
Te falta la annotation **@Repository**

2022-03-19 02:09 UTC, turcoamado commented on src/main/resources/application.properties
> +spring.datasource.driver.class=com.mysql.jdbc.Driver
Este archivo no debería ser incluído en el commit, es propio de cada configuración local

2022-03-19 02:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Role.java
> +    @NotNull
Para los atributos que marcas como **@NotNull** incluí también los mensajes de errores correspondientes (menos para el id claro, ya que ese nunca será input para la creación, se genera solo

2022-03-19 02:41 UTC, lucianoLattante commented
Perfecto ! Ahora cambio

2022-03-20 15:20 UTC, turcoamado approved these changes
Joya! ahora si! disculpame la demora

2022-03-20 15:20 UTC, turcoamado commented on .gitignore
> +src/main/resources/application.properties
Buenisimo esta agregación!

2022-03-21 03:15 UTC, merged