adding dto,services, controller
alkemyTech/OT167-Java-server pull request #16
Opened 2022-03-21 04:44 UTC by lucianoLattante

2022-03-21 23:21 UTC, turcoamado requested changes
El mapper ponelo en la carpeta donde acordamos, fijate que tenés una dependencia dos veces en el pom.

Y si queres habla con Facu que hizo toda la implementación de JWT, vas a necesitar de su parte para poder probar esto

2022-03-21 23:21 UTC, turcoamado commented on pom.xml
> +		</dependency>
pusiste dos veces la misma dependencia

2022-03-21 23:23 UTC, lucianoLattante commented on pom.xml
> +		</dependency>
Dale, Muchas gracias! ahora hablo con el

2022-03-22 02:54 UTC, lucianoLattante commented
Ahi hicimos eso con facu

2022-03-22 03:22 UTC, turcoamado approved these changes
Buenísimo!!
Consulta, la dependencia que dejaste comentada. es por algo en particular? Si no la vamos a utilizar la sacaría, para no ensuciar.
Te dejo aprobado el PR, fijate eso nomas y listo, podes mergear tranqui

2022-03-22 03:37 UTC, lucianoLattante commented
> Buenísimo!! Consulta, la dependencia que dejaste comentada. es por algo en particular? Si no la vamos a utilizar la sacaría, para no ensuciar. Te dejo aprobado el PR, fijate eso nomas y listo, podes mergear tranqui

Nono, copie el pom de facu, no se porque la comento el, pero tenia dependencias de Json asique tuve que copiarme su pom, ahora lo cambio y mergeo nomas

2022-03-22 03:39 UTC, merged