Create json web token
alkemyTech/OT167-Java-server pull request #17
Opened 2022-03-21 13:03 UTC by facuvillalba

Class HelloResource  is an example only for postman to verify token generation. Will be deleted.
La clase HelloResorce es un ejemplo solamente para postman pera verificar la generación del token. Será borrado.

2022-03-21 23:19 UTC, turcoamado requested changes
Lo que hiciste está muy bien, pero creo como dijiste es más de lo que pide el ticket. Lo que haría es lo siguiente, create una nueva rama a partir de esta y dejala ahi por las dudas, por si en algún momento necesitamos referencia a esto.

Y luego volvete a esta y dejate lo que te dejo a continuación 
pom.xml
SecurityConfiguration.java
JwtRequestFilter.java
JwtUtils.java

Es decir, las modificaciones que realizaste para testearlo no sería necesarias, pero fijate en todo caso de hablar con Luciano que está con la tarea de devolver los datos del usuario autenticado, él va a necesitar esto que hiciste vos

2022-03-22 03:56 UTC, turcoamado requested changes
Te restaría únicamente sacar **UserDetailsService** y lo que te comenté de esa dependencia comentada, que se lo vi en el PR a Luciano.
Por las dsudas traete lo último de develop luego de sacar el UserDetailsService

2022-03-22 03:56 UTC, turcoamado commented on pom.xml
> +		<!--<dependency>
Esta dependencia por qué está comentada? Si no se va a utilizar la eliminaría para no ensuciar el código

2022-03-22 04:03 UTC, turcoamado approved these changes
Te dejo el PR como aprobado, pero no te olvides de sacar la clase **UserDetailsService** antes de hacer el merge

2022-03-22 17:58 UTC, facuvillalba commented
The class UserDetailsService  should be deleted.
Se deberá borrar la clase UserDetailsService.

2022-03-22 18:00 UTC, merged