Feature/ot167 24
alkemyTech/OT167-Java-server pull request #23
Opened 2022-03-22 19:25 UTC by mickaelatarazaga

Yami revisá el tema de los roles, no estoy segura de haberlo hecho como corresponde y estoy atenta a cualquier otra corrección.

Saludos

2022-03-22 22:27 UTC, turcoamado requested changes
A nivel requerimientos el PR está bien, y también es correcta la encriptación de la password. Lo validaste en la DB?

Lo que te marqué son pavadas que hacen a las buenas prácticas, nombres de métodos que comiencen con minúscula, variables de clase privadas, role que está como rol y creo que nada más.

2022-03-22 22:27 UTC, turcoamado commented on pom.xml
> +	 <dependency>
por qué esta dos veces esta dependencia?

2022-03-22 22:27 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/AuthenticationController.java
> +    UserService userService;
Es una bunea práctica las variables de clase como privadas, serían públicas si estamos en un contexto estatico y queremos acceder a esa variable desde otra clase

2022-03-22 22:27 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/UserRegisterRequest.java
> +    @Email(message = "Email should be valid.", regexp = "[A-Za-z0-9._%-+]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}")
Muy buena la validación con la regex

2022-03-22 22:27 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/UserRegisterRequest.java
> +    @Size(min = 6, message = "Password must be between 6")
Una pavada pero el menasje de error está mal, between significa entre, y la validación dice que es un mínimo de 6 caracteres, por lo que debería decir algo como: "The password must be at least 6 characters"

2022-03-22 22:27 UTC, turcoamado commented on src/main/java/com/alkemy/ong/exception/DataAlreadyExistException.java
> +    public DataAlreadyExistException (String message) {
El nombre del método debería empezar con minúscula

2022-03-22 22:27 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/UserMapper.java
> +    PasswordEncoder passwordEncoder;
Lo mismo que te mencioné antes con la variable de clase, debería ser privada

2022-03-22 22:27 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/UserMapper.java
> +        List<Role> rol = new ArrayList<>();
role en lugar de rol

2022-03-22 22:27 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/UserMapper.java
> +    public User UserRegisterRequestDto2User(UserRegisterRequest userDto) {
Los métodos deben comenzar con minúscula, fijate que en esta clase están casi todos comenzando con mayúscula (incluso uno que estaba antes y se me pasó, haceme el favor y cambialo también porfa)

2022-03-22 22:27 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +    UserRepository userRepository;
Variables privadas!

2022-03-23 04:23 UTC, turcoamado requested changes
Me había confundido yo en una observación, te pido disculpas, pero ya te lo solucioné, realicé un refactor de algo que ya tenías y lo commite y pushee.

Te propuse que hagas un merge contra develop así te traés lo que se implementó para los mensajes y cambias el que tenes hardcoded en UserServiceImpl.

De todos modos el PR está muy bien.

2022-03-23 04:23 UTC, turcoamado commented on src/main/java/com/alkemy/ong/exception/dataAlreadyExistException.java
> +public class dataAlreadyExistException extends Exception {
Acá me confundí yo, te pido disculpas, es más voy a ver si te lo acomodo yo. Me mareé cuando lo leí, pero ahora veo que en realidad es un constructor lo que está dentro, por lo tanto está bien que sea en mayúscula, de hecho cuando refactorizaste te modificó todos los throws.
Disculpas nuevamente

2022-03-23 04:23 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +            throw new DataAlreadyExistException("This email is already registered");
Hacete un merge con develop y fijate de implementar lo nuevo para los mensajes

2022-03-23 15:38 UTC, mickaelatarazaga commented
Buen día Yami, como estás? Ya realicé los cambios que me sugeriste e implementé lo de los errores.
Igualmente fijate si está bien.

Saludos

2022-03-23 21:22 UTC, merged