Creation of the model and base repository of Members
alkemyTech/OT167-Java-server pull request #3
Opened 2022-03-17 22:44 UTC by mickaelatarazaga

2022-03-19 01:26 UTC, turcoamado requested changes
Muy bueno el historial de commits

2022-03-19 01:26 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Members.java
> +    private String name;
Tanto en este como en los demas campos que estás anotando como **@NotNull** te falta el mensaje de error que podrías incluír

2022-03-19 01:26 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Members.java
> +    private LocalDate dateCreated;
Además podrías utilizar la annotation **@CreationTimestamp** para la creación

2022-03-19 01:26 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Members.java
> +    private LocalDate dateModified;
y en este caso podrías utilizar la annotation **@UpdateTimestamp**

2022-03-20 14:46 UTC, mickaelatarazaga commented on src/main/java/com/alkemy/ong/model/Members.java
> +    private LocalDate dateCreated;
Hola Yami, como estás? Mira no entiendo bien a que haces referencia con que utilice la annotation @CreationTimestamp para la creación y @UpdateTimestamp ya que si las estoy utilizando. 
Están de forma incorrecta? O querés decir que borre la annotation @Column? Si podés explicarme te lo agradezco..

2022-03-20 15:27 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Members.java
> +    private LocalDate dateCreated;
Mika como andas? Perdoname, se ve que tenía dos PRs abiertos y escribí en el tuyo en lugar del otro. Está bien así como lo tenés! La columna @Column es necesaria porque le indicas a la DB que es una columna de la tabla.
Me confundí yo en la corrección.

2022-03-20 15:29 UTC, turcoamado requested changes
Perdoname que me confundí con lo que te dije de los Timestamp.
Te falta la annotation en el repository y el mensaje de error en los @NotNull

2022-03-20 15:29 UTC, turcoamado commented on src/main/java/com/alkemy/ong/repository/MembersRepository.java
> +public interface MembersRepository extends JpaRepository<Members, Long>{
Te falta la annotation @Repository acá

2022-03-20 16:29 UTC, mickaelatarazaga commented
I already made the changes

2022-03-21 02:16 UTC, turcoamado approved these changes
Joyaaaa

2022-03-21 13:24 UTC, merged