edit an organization
alkemyTech/OT167-Java-server pull request #36
Opened 2022-03-25 03:04 UTC by britomluz

- edit Organization method in OrganizationController
- edit Organization method in OrganizationService
- new bad request in exception package
- new message in message.properties

2022-03-26 19:15 UTC, turcoamado requested changes

2022-03-26 19:15 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        Organization organization = organizationRepository.findById(id).orElse(null);
Chequeaste que pasa si el id no existe? SI dejas que el usuario mande un parámetro hay que chequear siempre los posibles errores, si en este caso le metemos un id que no existe la búsqueda va a traer un null por como lo estas definiendo, eso no está mal, pero fijate que luego a este objeto que trajimos le estás haciendo una serie de sets, ahí te va a explotar porque estas intentando setearle un atributo a un objeto que es null.
En ese caso deberías manejar eso para que la aplicación no explote, sino que tire un 404 indicando que no se encontró lo buscado.

Ahora, como para nosotros va a existir una única organization como entidad, no debería ser necesario ni siquiera que el usuario tenga que indicar el id de la organization que quiere traer, fijate que incluso Jira te dice que la ruta es  _/organization/public_ 

Entonces, lo que haría yo en este caso sería un getAll() quizás y un filter para que me traiga el primero que agarra, ya que podemos asumir que siempre tendremos una sola, de todos modos en el código es buena práctica que esté el manejo de un posible null aunque no lo vayamos a tener.

2022-03-30 00:11 UTC, britomluz commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        Organization organization = organizationRepository.findById(id).orElse(null);
lo resolvi con un findAll().get(0) y resuelvo el null ya que no hace falta que sea un Optional

2022-03-30 22:21 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        Organization organization = organizationRepository.findById(id).orElse(null);
buenisimo!

2022-03-30 22:21 UTC, turcoamado approved these changes
Ahora si!

2022-03-30 22:21 UTC, merged