Security develop
alkemyTech/OT167-Java-server pull request #37
Opened 2022-03-25 17:06 UTC by mickaelatarazaga

Hola Yami, como estás? Mira estuvimos hablando con Victor de hacer unos cambios en la parte de seguridad, para el registro de usuarios y de paso aproveche para realizar algunas correcciones.
La parte de roles todavía no se bien como asignarla al crear un usuario, por eso lo dejo comentado y pendiente.
Hice las pruebas con Postman para ver si el registro estaba funcionando, te dejo las capturas..

![image](https://user-images.githubusercontent.com/94411297/160167472-fd539a46-b009-486b-8d01-8590bb3dd911.png)

![image](https://user-images.githubusercontent.com/94411297/160167534-7bda9537-bd1e-4183-be31-0bd2c2018435.png)

Está bien devolver ese status code si el usuario ya se registro con el mismo correo?

Y en la base de datos encripta la contraseña correctamente.

Avisame si hago algún cambio o directamente lo puedo pasar a develop para seguir trabajando desde ahi.

Saludos

2022-03-26 19:56 UTC, turcoamado requested changes
Buenísimo el PR Mika! Excelente las imágenes de Postman también, muy claras. 
Con respecto a tu consulta, si está bien devolver el status code en ese caso ya que estamos identificando un error (siempre se debe devolver en realidad, luego vemos como lo usamos, lo importante es ver cual devolver para ser consistentes con lo que estamos haciendo en caso de éxito o error).

No entendí por qué se agregó el archivo [nbactions.xml]

Te dejé una alternativa de como podes hacer lo de Roles, aunque no estaba mal lo que habías planteado tampoco.

2022-03-26 19:56 UTC, turcoamado commented on nbactions.xml
> +<?xml version="1.0" encoding="UTF-8"?>
para qué exactamente estás utilizando este archivo? Perdón pero ni recuerdo de haberlo tenido que tocar alguna vez

2022-03-26 19:56 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/controller/UserAuthController.java
> +    public ResponseEntity<UserEntity> logIn(@Valid @RequestBody UserDtoCreator userDto) throws Exception {
Buenísimo esto! Y se evitan la confusión de lo que charlamos ayer entre usar User para esto y para la entidad que modelaron

2022-03-26 19:56 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/UserDetailsCustomService.java
> +    public UserDetails loadUserByUsername(String userName) throws UsernameNotFoundException {
Este método ya se puede eliminar verdad? O en todo caso hacerlo bien, no tiene mucho sentido que se llame loadUserByUserName y que me esté devolviendo un usuario nuevo

2022-03-26 19:56 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
>          return Optional.ofNullable(userRepository.findById(id).orElseThrow(() -> new NotFoundException(messageSource.getMessage("user.not.found",null, Locale.ENGLISH))));
Está muy bueno que usen este tipo de expresiones, agregar las funciones lambda es una muy buena práctica y van a ver que si se acostumbran a utilizarlas les va a facilitar bastantes cosas

2022-03-26 19:56 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/mapper/UserMapper.java
> +//        List<Role> role = new ArrayList<>();
No está mal, podría ser una alternativa, pero creo que mejor si ya utilizamos lo que tenemos en el repositorio, porque se supone que deberíamos tener cargados los diferentes tipos de roles (y para esto estaría genial tener un Enum con los roles).

Entonces te voy a dejar acá como lo haría yo por ejemplo.

Tendría un Enum para roles, el lugar donde lo ubican puede ser en un package enum o dentro de security, Ahí no se si cambia realmente algo de la prolijidad.
```
public enum RoleEnum {
	ADMIN("ADMIN"), USER("USER");

	private final String name;
	private static final String ROLE_ = "ROLE_";

	RoleEnum(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public String getRoleName() {
		return ROLE_ + name;
	}
}
```
Entonces a tu lista de roles le agregaría el USER que saco del Enum
```
List<Role> roleList = new ArrayList<>();
roleList.add(roleService.findByName(RoleEnum.USER.getName()));
```

Y luego en la línea **57** donde seteas los roles
`user.setRole(roleList);`

Y de paso este enum les serviría cada vez que tengan que realizar algo con roles.

2022-03-28 12:43 UTC, mickaelatarazaga commented on nbactions.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Buen día Yamil, como estás? no me di cuenta que pushee este archivo, la verdad no se de donde salió.

2022-03-28 12:44 UTC, mickaelatarazaga commented on src/main/java/com/alkemy/ong/security/service/UserDetailsCustomService.java
> +    public UserDetails loadUserByUsername(String userName) throws UsernameNotFoundException {
Con respecto a este método, lo hizo otro compañero no se bien con que función pero voy a consultar si lo puedo borrar

2022-03-28 15:16 UTC, mickaelatarazaga commented
Ya realicé las correcciones, el método loadUserByUsername lo modifiqué porque se utiliza en el filtro.
También implementé lo de los Roles como me dijiste..

2022-03-28 21:35 UTC, turcoamado approved these changes
bararo!

2022-03-29 11:19 UTC, merged