feature OT167-30
alkemyTech/OT167-Java-server pull request #38
Opened 2022-03-26 02:32 UTC by kbza91

![Captura de pantalla (5)](https://user-images.githubusercontent.com/54422862/160221456-ffa0294a-dee4-4bf7-b5ed-2fdb3047e93e.png)

2022-03-26 20:28 UTC, turcoamado requested changes
Está muy bien, pero te comenté algo sobre el id que le estás pasando al registerUser que entiendo es el de la organization.

Bueno, consideraría no pasarlo y no tener más de una sola organización, leete el comentario y cualquier cosa me consultas, pero pueden debatirlo como equipo para ver si quieren hacer que la aplicación soporte más de una organización o sólo una, ya que está ambiguo en sus requerimientos con respecto a esto me parece.

2022-03-26 20:28 UTC, turcoamado commented on src/main/java/com/alkemy/ong/enums/MailMessage.java
> +package com.alkemy.ong.enums;
Está muy bien esta clase! Fijate que @AndrRod en el PR https://github.com/alkemyTech/OT167-Java-server/pull/35 propone agregar algunos de estos mensajes en el message_en.properties, que tampoco me parece mal. Pero ponganse de acuerdo.

2022-03-26 20:28 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/controller/UserAuthController.java
> -    public ResponseEntity<UserDto> findUserById(@PathVariable Long id){
Por qué estás eliminando este endpoint? No era solicitado? No entiendo, alguna funcionalidad seguramente estamos rompiendo acá

2022-03-26 20:28 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> -    public Optional<User> findUserById(Long id) {
No entiendo por qué estas eliminando este método, no se usa más? Ojo al eliminar, primero hay que chequear que no se esté rompiendo nada

2022-03-26 20:28 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/EmailServiceImpl.java
> +    private String preparedWelcomeBodyEmail(User user, Long id) {
Ah bien, acá entendí lo del id, es el id de la organization. Bien, bueno no tampoco es necesario, vamos a considerar que tenemos una sola organización entonces siempre estamos siempre creando cosas sobre ésta. Si quieren interpretarlo de otra manera ningún problema, pero se torna bastante más complejo y deben ponerse de acuerdo, mi recomendación es que simplifiquen dado que no está especificado.
Para buscar la organization si es que usamos una sola, podes directamente hacer un _findAll()_ y luego haces un get del primero que encuentres, un findFirst() o algi así, total siempre vamos a considerar tener uno solo, se debería tener el tratamiento en el caso de que sea null, para mantener una buena práctica, es decir si traje un null mostrar un error 404

2022-03-26 20:28 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/controller/UserAuthController.java
> +    public ResponseEntity<UserRegisterResponse> registerUser(@Valid @RequestBody UserRegisterRequest userReq, @RequestParam Long id) throws DataAlreadyExistException, IOException {
Esto no es correcto, cuando yo me regstro no debo pasarle nunca ningún id por parámetro, los id son generados automáticamente y de forma incremental, quién consume el endpoint nunca va a saber el id del usuario que se va a generar cuando ingreso los datos. Si por alguna razón necesitase el usuario que se acaba de crear, o alguno de sus datos, más adelante se debe agarrar al usuario creado y buscarlo en el repositorio

2022-03-29 00:17 UTC, kbza91 commented
Turco ya lo subí con las correcciones que me habias pedido. La parte de los mensajes todavia no lo modifique porque estoy esperando que haga merge Andres para aprovechar esos archivos y no se generen conflictos

2022-03-29 23:19 UTC, merged