Create model and repository of Testimonials
alkemyTech/OT167-Java-server pull request #4
Opened 2022-03-18 01:23 UTC by kbza91

2022-03-19 01:24 UTC, turcoamado requested changes

2022-03-19 01:24 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +@SQLDelete(sql = "UPDATE testimonials SET delete = true WHERE id = ?")
Ojo que aca estás escribiendo **delete** (y en el where también) y la variable que estás declarando se llama **deleted**, tienen que llamarse de la misma manera (utilizá deleted)

2022-03-19 01:24 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    @NotNull
Tanto en este como en los demas campos que estás anotando como **@NotNull** te falta el mensaje de error que podrías incluír

2022-03-19 01:24 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    private LocalDate updateDate;
y en este caso podrías utilizar la annotation **@UpdateTimestamp**

2022-03-19 01:24 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    private LocalDate creationDate;
Además podrías utilizar la annotation **@CreationTimestamp** para la creación

2022-03-19 15:36 UTC, kbza91 commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    private LocalDate updateDate;
Turco, consulta. La anotación que mencionas esta en el código, al igual que la de @CreationTimestamp. Estan bien escrita o es otro mi error

2022-03-20 15:22 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    private LocalDate updateDate;
Que raro, me confundí disculpame. Quizás tenía dos PRs abiertos diferentes y te escribí a vos en lugar de a otro

2022-03-20 15:23 UTC, turcoamado approved these changes
Listo! Disculpame la demora y el error en la corrección

2022-03-23 00:50 UTC, merged