Feature/ot167 39
alkemyTech/OT167-Java-server pull request #42
Opened 2022-03-27 23:51 UTC by lucianoLattante

2022-03-27 23:53 UTC, lucianoLattante commented
Ahi vimos con Micka el tema del service para subir imagenes

2022-03-28 00:28 UTC, turcoamado requested changes
El PR se ve bien, pero no veo la clase **amazonS3Configuration**, está en otro PR? Según el import está en el package config, pero en el código actualmente no está.

2022-03-28 00:28 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/PhotoServiceImpl.java
> +    private AmazonS3Configuration amazonS3Configuration;
No veo esta clase, está en otro PR?

2022-03-28 00:30 UTC, lucianoLattante commented on src/main/java/com/alkemy/ong/service/impl/PhotoServiceImpl.java
> +    private AmazonS3Configuration amazonS3Configuration;
Hola, si esa era la parte de Micka, está en su rama

2022-03-28 00:31 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/PhotoServiceImpl.java
> +    private AmazonS3Configuration amazonS3Configuration;
Ah perfecto entonces! Te lo dejo aprobado, fijense como coordinan con los merge y listo.

2022-03-28 00:32 UTC, turcoamado approved these changes

2022-03-28 00:37 UTC, lucianoLattante commented on src/main/java/com/alkemy/ong/service/impl/PhotoServiceImpl.java
> +    private AmazonS3Configuration amazonS3Configuration;
Joya! muchas gracias

2022-03-28 03:23 UTC, merged