Initial commit, add list of categories by name
alkemyTech/OT167-Java-server pull request #47
Opened 2022-03-29 19:51 UTC by facuvillalba

Hola Yamil envío capturas de Postman
Creando categorías (POST)

![image](https://user-images.githubusercontent.com/92343172/160695207-8ae6080e-0a6f-48d6-be5e-5bb84fb122a9.png)

Lista de Categorías por nombre(GET)

![image](https://user-images.githubusercontent.com/92343172/160695313-5a74abc0-b79f-46ba-8c90-13f96d5c3542.png)

2022-03-29 22:22 UTC, turcoamado requested changes

2022-03-29 22:22 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        for (CategoryDto categoryDto : listAllCategoryDto){
Para esto tambien podrias haber utilizado una expresion lambda, y quedaria algo como
```
listAllCategoryDto.forEach(category -> {
       listcategoriesByName.add(categoryDto.getName());
}
```
incluso podria resolverse casi en una sola linea como
```
return listAllCategoryDto.stream()
               .map(categoryDto ->  categoryDto.getName())
               .collect(Collectors.toList())
}
```
Esto ultimo chequealo porque estoy muy en el aire, codee aca y quizas me estoy olvidando de algo.
De todos modos lo que hiciste no esta mal, es simplemente intentar mostrarte que hay otra forma incluyendo programacion funcional

2022-03-30 01:14 UTC, facuvillalba commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        for (CategoryDto categoryDto : listAllCategoryDto){
Pude hacer la última propuesta. Voy a investigar más sobre esto. Muchas gracias

2022-03-30 01:15 UTC, facuvillalba commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        List<String> ListcategoriesByName = new ArrayList<>();
Si perdón no sé cómo se me pasó.

2022-03-30 01:15 UTC, facuvillalba commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +/*    private String validate(String parameter) throws IncorrectPatternExeption {
Ese método estaba en otra rama (PR). Utilicé el Mapper de esa rama para crear una categoría para probar en Postman. Comenté ese método y me olvidé de borrarlo.  Voy a preguntar por si no está mergeado.

2022-03-30 22:24 UTC, turcoamado approved these changes
Excelente! Espero que hayas entendido mas o menos como funcionan las expresiones lambda, si te acostumbras a utilizarlas te va a facilitar bastante cosas, y ademas es una muy buena practica

2022-03-31 18:28 UTC, merged