OT167-44: Creation path of DELETE /categories/:id
alkemyTech/OT167-Java-server pull request #50
Opened 2022-03-30 01:45 UTC by AndrRod

Turco como andas cree los métodos en las capas relacionadas al delete de categorias por id.

Respuestas Postman:
En caso de delete exitoso
![category3](https://user-images.githubusercontent.com/79908280/160733983-ab11e267-5c70-4735-992a-823e31772d99.png)

En caso de no encontrar la entidad a borrar
![categoria1](https://user-images.githubusercontent.com/79908280/160734072-837bf365-3143-4920-8473-a9e141420eb0.png)

En caso de colocar un parametro no deseado
![categoria2](https://user-images.githubusercontent.com/79908280/160734122-d326fcbb-2e57-4d47-bffc-60585a5193e8.png)

Tal vez a parte de este trabajo, tengo que hablar con Agus creo, porque tuve unos inconvenientes para crear la entidad pasando por el dto creado.

2022-03-30 22:42 UTC, turcoamado requested changes
Me gusta que hayas probado varios casos de error, pero para el ultimo el del id sarasa, el mensaje de error deberia ser otro, imaginate que al usuario no le interesa todo eso porque posiblemente ni entienda el tipo de error (pensemos en un usuario final y no en quien consume el endpoint)
Entonces, deberia ser algo mas claro, para mi iria el mismo mensaje que en el 403, es mas, el error deberia ser ese, porque no tendria por que explotar la aplicacion si meto fruta en el id.

Te muevo la tarea en Jira a DONE, pero corregite esto y los conflictos porfa

2022-03-30 22:42 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +        Map<String, String> message = new HashMap<>(){{put("message: ", messageSource
Esto esta muy piola, que indiques que elemento fue borrado con un mensaje de exito

2022-03-30 22:49 UTC, AndrRod commented
Dale Turco ahi ya lo modifico en una disparada. Gracias

2022-03-31 03:33 UTC, turcoamado approved these changes
Bien, me gusta la validacion!

2022-03-31 21:08 UTC, merged