Feature/ot167 65
alkemyTech/OT167-Java-server pull request #58
Opened 2022-04-01 00:54 UTC by mickaelatarazaga

Yami buenas noches, hice la modificación que nos sugeriste por el grupo de devolver un mensaje.

![image](https://user-images.githubusercontent.com/94411297/161173639-c0be8ec7-98da-4406-86e5-92ba374183a4.png)

![image](https://user-images.githubusercontent.com/94411297/161173376-7d83fe78-babe-4bd9-b327-4231a652471a.png)

Saludos

2022-04-02 18:01 UTC, turcoamado requested changes
Te marqué una pavada en el message.properties. Y algo no me cierra de los mensajes de error, como que se repite un campo, podes chequear eso porfa? Es un detalle el PR técnicamente está bien

2022-04-02 18:01 UTC, turcoamado commented on src/main/resources/messages/message_en.properties
> +member.name.empty=The name cant be empty o null
a este cant't le falta el apostrofe

2022-04-03 12:51 UTC, mickaelatarazaga commented on src/main/resources/messages/message_en.properties
> +member.name.empty=The name cant be empty o null
Yami el campo que agregué yo fue el de Testimonial, el otro ya estaba en develop que lo había agregado Andrés, pero igualmente lo corrijo y lo envío.

2022-04-03 12:57 UTC, mickaelatarazaga commented
Listo Yami, ya arreglé el error de ortografía y resolví ese conflicto (nunca agregué esa línea, solo me la traje de develop no se porqué aparecía doble)

2022-04-04 01:48 UTC, turcoamado approved these changes

2022-04-04 11:31 UTC, merged