adding Comment: DTOs,Service methods,Controller and Mapper
alkemyTech/OT167-Java-server pull request #61
Opened 2022-04-01 03:03 UTC by lucianoLattante

2022-04-01 03:12 UTC, lucianoLattante commented
Hola turco, ahi esta el controller para agregar nuevos comments
![xd1](https://user-images.githubusercontent.com/91094677/161188066-68e633ae-6b6c-4479-a1a0-1d57c8294c8c.png)
![xd2](https://user-images.githubusercontent.com/91094677/161188075-f48ee7b9-3c4c-4d1e-83be-6c19390f14a9.png)

2022-04-02 18:20 UTC, turcoamado requested changes
Lo que estás devolviendo como error 500 es si el usuario se olvida de ingresar algún parámetro verdad? Eso no debería ser un 500, porque el error es arrojado por el servidor pero a partir de que hay algo que no se envió, te está explotando seguramente porque no tiene a donde ir a guardar ese comentario.
El error debería ser un bad request indicando qué campo/s es/son faltante/s. Lo que no entiendo bien es por qué arroja este error si veo que lo estás manejando. Podrás revisarlo?

2022-04-02 18:20 UTC, turcoamado commented on src/main/resources/messages/message_en.properties
> +member.name.empty=The name cant be empty o null
A este can't le falta un apóstrofe, lo vi en otros PRs, no se a quién exactamente le corresponde la corrección ni por qué me está saltando en varios como que los cambios son en cada PR. Pero charlen y vean quién lo acomoda nada más.

2022-04-02 18:51 UTC, lucianoLattante commented on src/main/resources/messages/message_en.properties
> +member.name.empty=The name cant be empty o null
Hola , no pasa nada, no se quien lo hizo pero yo lo cambio no hay problema

2022-04-02 19:38 UTC, lucianoLattante commented
Hola turco, ahi hice un par de pruebas y el error lo esta manejando bien, yo cambie un par de cosas que por ahi se estaban rompiedo pero lo tira como error 500, el messageSource funciona bien aunque me tira error 500

2022-04-02 19:41 UTC, lucianoLattante commented
Ahi lo resolvi, era que no estaba usando el manejador de excepciones para el controller entonces no lo manejaba correctamente, ahora si lo hace. ahi te muestro como queda ahora.

2022-04-02 20:09 UTC, lucianoLattante commented
![p1](https://user-images.githubusercontent.com/91094677/161399512-9c54374f-5dc3-43af-b29a-775120b17940.png)
![p2](https://user-images.githubusercontent.com/91094677/161399515-66504b50-6061-4196-99cd-857cac54c156.png)
![p3](https://user-images.githubusercontent.com/91094677/161399519-46179d55-482e-4b0f-8d4a-80906a066f80.png)
![p4](https://user-images.githubusercontent.com/91094677/161399521-20ffe1cc-b657-442f-81aa-da2ea90cb212.png)

2022-04-04 01:49 UTC, turcoamado approved these changes
Barbaro!!

2022-04-04 23:09 UTC, merged