adding dataseeder
alkemyTech/OT167-Java-server pull request #68
Opened 2022-04-03 21:00 UTC by lucianoLattante

Hola turco, no se si se podra hacer de otra manera el seeder pero esto es lo que pude hacer

2022-04-04 02:04 UTC, turcoamado requested changes
Lucho como estas? Está bien esto! Lo único, ponele datos relacionados con la ONG, en el campus debes tener seguramente el objetivo y debe decir qué tipo de actividades realizan, chantale dos o tres de esas como para que parezca real. Y debería cargar una imagen posta en vez de ponerle un string "image"

2022-04-04 02:06 UTC, lucianoLattante commented
> Lucho como estas? Está bien esto! Lo único, ponele datos relacionados con la ONG, en el campus debes tener seguramente el objetivo y debe decir qué tipo de actividades realizan, chantale dos o tres de esas como para que parezca real. Y debería cargar una imagen posta en vez de ponerle un string "image"

Sisi,lo hice de prueba porque no sabía de donde sacar los datos de la ONG

2022-04-05 03:18 UTC, lucianoLattante commented
Ahi le agregue datos que saque del proyecto y tambien le puse urls como me dijiste con lo de la imagen

2022-04-06 03:26 UTC, turcoamado approved these changes

2022-04-06 03:53 UTC, merged