Feature/ot167 82
alkemyTech/OT167-Java-server pull request #83
Opened 2022-04-07 03:44 UTC by lucianoLattante

Turco, pude hacer la paginacion de 10, te dejo las imagenes de postman por si hace falta
Pagina 1: trae 10 members
![page1](https://user-images.githubusercontent.com/91094677/162115987-731467e7-a122-40d8-8c8e-6c6925e84073.png)

Pagina 2: trae 3 members (porque tengo 13 creados y todos iguales)
![page2](https://user-images.githubusercontent.com/91094677/162115993-86b5e977-adcf-4779-bc27-b3e1894d77ab.png)

2022-04-07 04:11 UTC, lucianoLattante commented
![page1part2](https://user-images.githubusercontent.com/91094677/162118507-9f94bea2-a906-4661-8535-3211c82aa8c8.png)
![page1part2](https://user-images.githubusercontent.com/91094677/162118513-8c2ea09c-8f54-49a1-ac9a-a4ada70fc3c0.png)
Ahi dropie la base de datos y la cree denuevo porque me estaba tirando error al crear e hice la verificacion y en estas imagenes se nota mas el cambio de pagina

2022-04-07 19:11 UTC, turcoamado requested changes
Está bastante bien! Te dejé un comentario en el controller de algo que debeŕia estar en el service.
En las imágenes que pasas no logro ver los links a las págs siguientes ni listado más de un usuario.

Fijate de todos modos el PR de Andrés y ponganse de acuerdo, así reutilizan cosas y queda todo más o menos similar.

2022-04-07 19:11 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +        Integer page = params.get("page") != null ? (Integer.valueOf(params.get("page").toString()) -1) : 0;
Esta lógica que pones acá debería esstar en el service, recibís el número de página por parámetro (en este caso vos lo planteas con **params**) y le pasas eso al service, allí es el lugar para realizar las operación del PageRequest.of(). Y si le pasas el map entonces la page la recuperás también en el service, es decir lo que tenés en la línea 45.

2022-04-07 23:08 UTC, lucianoLattante commented
https://user-images.githubusercontent.com/91094677/162333485-cb7d5a7a-c18d-4c1b-be61-03d1eb86240a.mp4

Turco, ahi quedo, me pullie lo de develop asi ya tenia el mismo mensaje que uso andres y asi quedo! se ve bastante bien en el gif creo

2022-04-07 23:09 UTC, lucianoLattante commented
Ahi al final me di cuenta que retornaba 9 asique cambie el page size a 10 y ahora retorna 10

2022-04-08 03:42 UTC, turcoamado approved these changes
Buenisimo!

2022-04-08 03:43 UTC, merged