Feature/ot167 75
alkemyTech/OT167-Java-server pull request #93
Opened 2022-04-10 20:21 UTC by agusgar409

pedido de lista de comentarios ordenado por fecha de creacion

2022-04-11 03:17 UTC, turcoamado requested changes
De donde estas partiendo para hacer esto? Hay muchisimas clases modificadas y en tu PR deberian haber dos o tres nada mas, lo referente a comentarios.
Me asusta sobre todo las cosas que veo que se han eliminado, ojo con eso, probate bien todo?
Y te deje un comentario en algo si de tus cambios puntualmente que no logro entender bien

2022-04-11 03:17 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CommentMapper.java
> +        /*if(commentValidated.getNews_id()==null){
por que se estan comentando estas validaciones?

2022-04-11 03:17 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CommentMapper.java
>      private CommentDto Validate(CommentDto commentDto){
No entiendo, bien que paso aca. Por lo que veo en ralidad este metodo lo que hacia era armar el commentDto, pero validaba antes que no esten vacios los campos creo. Vos comentaste todas las validaciones del metodo, ahora no esta haciendo nada directamente, por que? que cambio? No entendi tampoco las lineas comentadas arriba (54 y 55)
De paso, si volves a tocar esto cambia el nombre del metodo, ponelo con v minuscula, si no va mas eliminalo, pero quisiera entender que pasa

2022-04-11 03:17 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CommentMapper.java
> +        return commentsList.stream().map(comments -> commentEntity2BasicDto(comments)).collect(Collectors.toList());
Esto esta muy bien!

2022-04-13 23:15 UTC, closed without merging

2022-04-13 23:16 UTC, agusgar409 commented
cree una nueva rama, con la informacion de esta, pero esta mas ordenada