OT167-78 - Endpoint Eliminación Comentarios
alkemyTech/OT167-Java-server pull request #97
Opened 2022-04-12 00:57 UTC by salvatierra1

**EVIDENCIA**

BASE DE DATOS

![image](https://user-images.githubusercontent.com/70789932/162856329-4d37d0d4-d924-4efb-a5db-72ab78d1e1f4.png)

![image](https://user-images.githubusercontent.com/70789932/162856388-85174b52-55ed-4313-8ac6-516df5278b3d.png)

POSTMAN

![image](https://user-images.githubusercontent.com/70789932/162856545-a8d90d4c-01a3-40f6-993d-2fb7d55d116b.png)

![image](https://user-images.githubusercontent.com/70789932/162856612-a92a6f75-e924-4714-bd54-7c0666e5ea91.png)

![image](https://user-images.githubusercontent.com/70789932/162856729-3a23cc9d-6329-4c06-b2d2-4c752dcaf4a4.png)

BASE DE DATOS

![image](https://user-images.githubusercontent.com/70789932/162856783-689e9fdc-9160-4101-91c1-0423ca6f1bf8.png)

POSTMAN CON OTRO USUARIO

![image](https://user-images.githubusercontent.com/70789932/162856935-557b35f4-aabc-4e61-8569-63138bf3e420.png)

![image](https://user-images.githubusercontent.com/70789932/162857004-55ea0836-29e8-4886-a736-1958ca8e247c.png)

![image](https://user-images.githubusercontent.com/70789932/162857029-0f2cd8d5-aa38-44b4-b949-7a929db32bc3.png)

2022-04-12 01:00 UTC, salvatierra1 commented
Perdón modifiqué el seeder la contraseña agregue mas caracteres, porque creo que tiene minimo 7. Despues agregué el deleted en la entidad comment.

2022-04-12 01:31 UTC, turcoamado requested changes
Víctor como va? Yo creo que no está mal lo que plantás, quizás podría hacerse más sencillo, pero me parece correcto los pasos que seguis para chequear si es posible eliminar el comentario.

Te marqué dos mejoras pero que no hacen al resultado del código sino a las buenas prácticas nada más.

2022-04-12 01:31 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +            if (username.equals(emailUserCreator) || authorityUser.equals("ROLE_ADMIN")) {
Este if lo podemos poner en una sola línea, queda así:
`return (username.equals(emailUserCreator) || authorityUser.equals("ROLE_ADMIN"))`

2022-04-13 21:37 UTC, turcoamado approved these changes

2022-04-14 15:47 UTC, merged